# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow and in the numpy documentation. The goal of this collection is to offer a quick reference for both old and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel free to open an issue at <https://github.com/rougier/numpy-100>

#### 1. Import the numpy package under the name `np` (★☆☆)

In [4]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [4]:
print(np.__version__)
np.show_config()

1.16.4
mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['D:/Anaconda\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'D:/Anaconda\\Library\\include']
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['D:/Anaconda\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'D:/Anaconda\\Library\\include']
blas

#### 3. Create a null vector of size 10 (★☆☆)

In [9]:
np.zeros([10])

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4.  How to find the memory size of any array (★☆☆)

In [12]:
np.zeros([10]).itemsize

8

#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆)

In [10]:
help(np.add)

Help on ufunc object:

add = class ufunc(builtins.object)
 |  Functions that operate element by element on whole arrays.
 |  
 |  To see the documentation for a specific ufunc, use `info`.  For
 |  example, ``np.info(np.sin)``.  Because ufuncs are written in C
 |  (for speed) and linked into Python with NumPy's ufunc facility,
 |  Python's help() function finds this page whenever help() is called
 |  on a ufunc.
 |  
 |  A detailed explanation of ufuncs can be found in the docs for :ref:`ufuncs`.
 |  
 |  Calling ufuncs:
 |  ===============
 |  
 |  op(*x[, out], where=True, **kwargs)
 |  Apply `op` to the arguments `*x` elementwise, broadcasting the arguments.
 |  
 |  The broadcasting rules are:
 |  
 |  * Dimensions of length 1 may be prepended to either array.
 |  * Arrays may be repeated along dimensions of length 1.
 |  
 |  Parameters
 |  ----------
 |  *x : array_like
 |      Input arrays.
 |  out : ndarray, None, or tuple of ndarray and None, optional
 |      Alternate array o

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [16]:
null_vector = np.zeros([10])
null_vector[4] = 1
null_vector

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆)

In [17]:
np.array(range(10,50))

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8.  Reverse a vector (first element becomes last) (★☆☆)

In [23]:
x = np.array(range(10))[::-1]
x

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [31]:
np.array(range(0,9)).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆)

In [33]:
temp = np.array([1,2,0,0,4,0])
np.nonzero(temp)

(array([0, 1, 4], dtype=int64),)

#### 11. Create a 3x3 identity matrix (★☆☆)

In [37]:
temp = np.identity(3)
temp

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [40]:
temp = np.random.random([3,3,3])
temp

array([[[0.87199874, 0.68919135, 0.7345355 ],
        [0.7772341 , 0.0337698 , 0.02111289],
        [0.04299447, 0.1358303 , 0.6780222 ]],

       [[0.97903327, 0.39951645, 0.55782855],
        [0.23667993, 0.88740313, 0.03248752],
        [0.41207738, 0.52009737, 0.50658422]],

       [[0.51005512, 0.58600663, 0.3394579 ],
        [0.13866302, 0.35001438, 0.15573106],
        [0.75418161, 0.26932759, 0.24571439]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [44]:
temp = np.random.rand(10, 10)
print(np.max(temp))
print(np.min(temp))

0.993196061894195
0.0018872844746850026


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [46]:
temp = np.random.rand(30)
np.mean(temp)

0.38272162531254295

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [50]:
temp = np.ones([5 ,5])
temp[1: -1, 1: -1] = 0
temp

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [65]:
temp = np.ones([5 ,5])
np.pad(temp, pad_width=1, mode='constant', constant_values=0)

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

#### 17. What is the result of the following expression? (★☆☆)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [76]:
0 * np.nan # nan
np.nan == np.nan #False
np.inf > np.nan #False
np.nan - np.nan #nan
np.nan in set([np.nan]) # True
0.3 == 3 * 0.1 # False; 3 * 0.1 =  0.30000000000000004

nan
False
False
nan
True
False
0.30000000000000004


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [24]:
help(np.diag)

Help on function diag in module numpy:

diag(v, k=0)
    Extract a diagonal or construct a diagonal array.
    
    See the more detailed documentation for ``numpy.diagonal`` if you use this
    function to extract a diagonal and wish to write to the resulting array;
    whether it returns a copy or a view depends on what version of numpy you
    are using.
    
    Parameters
    ----------
    v : array_like
        If `v` is a 2-D array, return a copy of its `k`-th diagonal.
        If `v` is a 1-D array, return a 2-D array with `v` on the `k`-th
        diagonal.
    k : int, optional
        Diagonal in question. The default is 0. Use `k>0` for diagonals
        above the main diagonal, and `k<0` for diagonals below the main
        diagonal.
    
    Returns
    -------
    out : ndarray
        The extracted diagonal or constructed diagonal array.
    
    See Also
    --------
    diagonal : Return specified diagonals.
    diagflat : Create a 2-D array with the flattened input 

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [28]:
temp = np.zeros([8, 8])
temp[1::2,::2] = 1
temp[::2,1::2] = 1
temp

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [46]:
temp = np.random.rand(6,7,8)
np.unravel_index(100, [6, 7, 8])
temp[1,5,4]

0.6041636654502448

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [61]:
temp = np.array([[0,1],[1,0]])
np.tile(temp, (4,4))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [63]:
temp = np.random.rand(5,5)
temp = (temp-np.mean(temp))/np.std(temp)
temp

array([[-0.9663631 ,  1.57431167, -0.71045788, -1.19773429, -0.88466633],
       [ 1.13884161,  1.48419196,  0.71063248, -0.94052875, -0.78746   ],
       [ 1.4885033 ,  1.03860322, -0.41361693, -0.99472175,  0.89426069],
       [ 0.42334642, -0.1758574 , -1.01110454,  1.47874296, -1.43666705],
       [-1.49319931, -0.07704925,  0.16640465,  0.58670682,  0.1048808 ]])

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

#### what's  the meaning of this 

In [69]:
np.dtype([('r', np.ubyte, 1),
         ('g', np.ubyte, 1),
         ('b', np.ubyte, 1),
         ('a', np.ubyte, 1)])

dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [70]:
matrix_a = np.random.rand(5, 3)
matrix_b = np.random.rand(3, 2)
result = np.dot(matrix_a, matrix_b)
result

array([[0.14583689, 1.08861501],
       [0.12593903, 0.93782349],
       [0.08365348, 0.79083991],
       [0.09535837, 0.66499636],
       [0.09691353, 0.66745058]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [88]:
temp = np.array(np.arange(10))
temp[(3 < temp) & (temp<= 8)] *= -1
temp

array([ 0,  1,  2,  3, -4, -5, -6, -7, -8,  9])

#### 26. What is the output of the following script? (★☆☆)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [102]:
print(sum(range(5),-1)) # python 原生的sum  ","后面的数字表示 x加上之前的求和此处为-1+0+1+2+3+4
print(np.sum(range(5),-1)) # np.sum ","后面的数字表示axis -1表示从里层的维度向外(from the last to the first)求和

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [115]:
Z = 4
Z**Z
2 << Z >> 2
Z <- Z  #小陷阱 应该是 Z < -Z
1j*Z # python中 1j 表示 -1 的平方根 此处为 4j
Z/1/1
Z<Z>Z

False

#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [125]:
np.array(0) / np.array(0) # 结果为nan
np.array(0) // np.array(0) # 结果为 0
np.array([np.nan]).astype(int).astype(float) # 结果为array([-2.14748365e+09]) 存疑？

D:\Anaconda\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.
D:\Anaconda\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  


array([-2.14748365e+09])

#### 29. How to round away from zero a float array ? (★☆☆)

In [142]:
Z = np.random.uniform(-10,+10,10)
print (np.copysign(np.ceil(np.abs(Z)), Z)) 
"""
np.copysign(a, b) 此函数作用为将 b array_like 中元素的符号 复制给 a array_like中的元素,若 b 为一个数则符号
复制给a全部元素， 若 a.shape != b.shape 必须将两者扩充到一致的shape
此处先对Z取绝对值，然后向上取整，最后通过 copysign 进行符号统一
"""

[-1.  8. -6.  2. -4.  2.  8.  3.  4.  5.]


#### 30. How to find common values between two arrays? (★☆☆)

In [151]:
matrix_a = np.array([1,2,3,4])
matrix_b = np.array([[1,1,2],[3,1,1]])
xy, x_index, y_index = np.intersect1d(matrix_a, matrix_b, return_indices=True)
xy, x_index, y_index 
"""
xy 表示 两个数组的相同元素
a，b 数组都被flatten到一维， x_index, y_index 各自表示相同元素在一维数组中的index
"""

(array([1, 2, 3]),
 array([0, 1, 2], dtype=int64),
 array([0, 2, 3], dtype=int64))

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [153]:
# Suicide mode on
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0

# Back to sanity
_ = np.seterr(**defaults)

# An equivalent way, with a context manager:

# 只在with环境中消除警告生效
with np.errstate(divide='ignore'):
    Z = np.ones(1) / 0

#### 32. Is the following expressions true? (★☆☆)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [156]:
np.sqrt(-1) == np.emath.sqrt(-1) # 前者 nan 且出发 warning， 后者结果为python原生复数1j emath表示自动配适数数域

1j

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [12]:
yesterday = np.datetime64('today') - np.timedelta64(1,'D')
today = np.datetime64('today')
tomorrow = np.datetime64('today') + np.timedelta64(1,'D')

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [17]:
np.arange('2016-07', '2016-08', dtype="datetime64[D]")

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆)

In [3]:
matrix_a = np.array([1, 2, 3], dtype='float')
matrix_b = np.array([2, 3, 4], dtype='float')
np.multiply(np.add(matrix_a, matrix_b), np.divide(-1 * matrix_a, 2), out=matrix_a)
matrix_a

array([ -1.5,  -5. , -10.5])

#### 36. Extract the integer part of a random array using 5 different methods (★★☆)

In [34]:
temp = np.random.uniform(0, 10, 10)
print(temp)
print(np.round(temp, decimals=0))
print(np.rint(temp))
print(np.ceil(temp))
print(np.trunc(temp))
print(temp.astype(np.int))
print(np.floor(temp))

[3.03580462e-03 1.76175676e+00 9.12275593e+00 6.75247381e+00
 1.71758223e+00 2.56920040e-01 2.11625481e+00 1.23337697e+00
 5.03551160e+00 3.67217327e+00]
[0. 2. 9. 7. 2. 0. 2. 1. 5. 4.]
[0. 2. 9. 7. 2. 0. 2. 1. 5. 4.]
[ 1.  2. 10.  7.  2.  1.  3.  2.  6.  4.]
[0. 1. 9. 6. 1. 0. 2. 1. 5. 3.]
[0 1 9 6 1 0 2 1 5 3]
[0. 1. 9. 6. 1. 0. 2. 1. 5. 3.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [51]:
np.repeat(np.array([np.arange(0,5),]).T, 5, axis=1)

array([[0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3],
       [4, 4, 4, 4, 4]])

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [57]:
iterable = (x for x in range(10))
print(np.fromiter(iterable, np.int)) # Create a new 1-dimensional array from an iterable object..
iterable = [x for x in range(10)]
print(np.array(list(iterable)))

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [61]:
np.linspace(0, 1, num=11, endpoint=False)[1:] 
"""
因为 np.linsacpe中的 "startpoint"总会包含，因此生成11个数排除第一个
"""

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

#### 40. Create a random vector of size 10 and sort it (★★☆)

In [65]:
print(np.sort(np.random.uniform(0, 10, 10)))
temp = np.random.uniform(0, 10, 10)
temp.sort() 
temp
"""
np.sort(array) 返回一个新的array
array.sort 就地改变原array 无返回值
"""

[0.51628996 0.64698511 1.91138092 2.14817952 3.95237092 5.29029087
 5.46685526 5.56670048 6.93291379 7.50895769]


array([0.50882334, 3.80763873, 3.86225399, 5.1867481 , 5.24164154,
       5.36321908, 5.81977964, 6.13398844, 6.5769454 , 9.80555975])

#### 41. How to sum a small array faster than np.sum? (★★☆)

In [77]:
temp = np.array([[1, 2, 3, 4],[2, 3, 4, 5]])
np.add.reduce(temp, axis=1)
"""
reduce函数将先将 add 应用于 第一第二个元素再将其结果运用在第三个元素上以此类推，以达到累加的目的，
根据题意在小数据量上此方法更快
"""
import time
start_time = time.time()
temp = np.array([[1, 2, 3, 4],[2, 3, 4, 5]])
np.add.reduce(temp, axis=1)
print('delta time(reduce) :{}'.format(time.time()-start_time))

start_time = time.time()
temp = np.array([[1, 2, 3, 4],[2, 3, 4, 5]])
np.sum(temp, axis=1)
print('delta time(sum) :{}'.format(time.time()-start_time))

delta time(reduce) :0.0
delta time(sum) :0.0


#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [81]:
matrix_a = np.random.rand(3, 2)
matrix_b = np.random.rand(3, 2)
np.array_equal(matrix_a, matrix_b)
np.allclose(matrix_a, matrix_b) 
"""
np.allclose 用于比较两个矩阵是否对应位置元素相等， 其中有atol和rtol两个参数可设置阈值来近似相等
"""

False

#### 43. Make an array immutable (read-only) (★★☆)

In [84]:
temp = np.array([1, 2, 3])
temp.flags.writeable = False #设置矩阵 read only   
temp[1] = .3

ValueError: assignment destination is read-only

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [129]:
temp = np.random.rand(10, 2)
result = np.array([np.sqrt(np.sum(temp**2, axis=1)), np.arctan2(temp[:, 1], temp[:, 0])]) 
# rho^2 = x^2 + y^2, theta = arctan (y/x)
result.T

array([[1.20419981, 0.96402021],
       [1.10809237, 0.89252971],
       [0.78801391, 0.52417839],
       [0.91445088, 1.10748723],
       [0.59200296, 0.31288491],
       [0.65422825, 0.22953092],
       [1.26323805, 0.8557284 ],
       [0.98500608, 0.46190392],
       [0.64362993, 0.90586301],
       [1.0525168 , 0.50255931]])

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [128]:
temp = np.random.rand(10)
temp[np.argmax(temp)] = 0
temp

array([0.63153334, 0.81218092, 0.87186948, 0.67769706, 0.        ,
       0.02424047, 0.70158982, 0.21446734, 0.39670187, 0.01334547])

#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆)

In [9]:
Z = np.zeros((5,5), [("x", 'float'), ('y', 'float') ])
Z['x'], Z['y'] = (np.linspace(0, 1, 5), np.linspace(0, 1, 5))
print(Z)

[[(0.  , 0.  ) (0.25, 0.25) (0.5 , 0.5 ) (0.75, 0.75) (1.  , 1.  )]
 [(0.  , 0.  ) (0.25, 0.25) (0.5 , 0.5 ) (0.75, 0.75) (1.  , 1.  )]
 [(0.  , 0.  ) (0.25, 0.25) (0.5 , 0.5 ) (0.75, 0.75) (1.  , 1.  )]
 [(0.  , 0.  ) (0.25, 0.25) (0.5 , 0.5 ) (0.75, 0.75) (1.  , 1.  )]
 [(0.  , 0.  ) (0.25, 0.25) (0.5 , 0.5 ) (0.75, 0.75) (1.  , 1.  )]]


####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

In [28]:
x = np.arange(8)
y = x + 0.5
C = 1.0 / np.subtract.outer(x, y)  # result
print(np.linalg.det(C))
"""
a = np.array([5,6,7])
b = np.array([9,12,10])
np.subtract.outer(b,a) 等价于 b[:,None]-a

array([[4, 3, 2],
       [7, 6, 5],
       [5, 4, 3]])
9-5=4；9-6=3；9-7=2
12-6=7；12-6=6；12-7=5
10-5=5；10-6=4；10-7=3
"""

3638.163637117973


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [29]:
integer = np.iinfo(np.int64)
print(integer.min, integer.max)
float_number = np.finfo(np.float64)
print(float_number.min, float_number.max, float_number.eps)
"""
eps即epsilon 表示浮点数能表示的最小精度
"""

-9223372036854775808 9223372036854775807
-1.7976931348623157e+308 1.7976931348623157e+308 2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆)

In [37]:
np.set_printoptions(threshold=100) # default threshold = 1000
Z = np.zeros((16,16))
print(Z)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [46]:
x = 5
matrix = np.random.randn(5)
print(matrix)
np.argmin(5 - matrix)

[-0.83493893 -1.74666815 -0.02199284  2.12718542  0.78095338]


3

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [55]:
Z = np.zeros(10, dtype = [('position', [('x', 'float'),
                                        ('y', 'float')]),
                           ('color', [ ('r', 'float'),
                                       ('g', 'float'),
                                       ('b', 'float') ])])
print(Z['position'])
print(Z['color']['r'])
"""
https://blog.csdn.net/qq_27825451/article/details/82425512
"""

[(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)
 (0., 0.) (0., 0.)]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [72]:
"""
构建矩阵，其元素为原矩阵中的两点距离
扩充一个维度后利用矩阵的转置构造对应距离
"""
import time
start_time = time.time()
temp = np.random.random([10, 2])
X, Y = np.atleast_2d(temp[:,0], temp[:,1])
distance = np.sqrt((X-X.T)**2 + (Y-Y.T)**2)
print(distance)
print('numpy:{}'.format(time.time()-start_time))
# faster
import scipy
# Thanks Gavin Heverly-Coulson (#issue 1)
import scipy.spatial
start_time = time.time()
Z = np.random.random((10,2))
D = scipy.spatial.distance.cdist(Z,Z)
print(D)
print('scipy:{}'.format(time.time()-start_time))

[[0.         0.57661714 0.51392078 0.24489269 0.60289054 0.3499818
  0.14747696 0.43536184 0.34558151 0.57217446]
 [0.57661714 0.         1.03943804 0.5041294  0.36853539 0.22683469
  0.46654722 0.96133948 0.76313566 0.01360061]
 [0.51392078 1.03943804 0.         0.54587014 0.90726716 0.8220723
  0.66136806 0.0795272  0.30785266 1.03144499]
 [0.24489269 0.5041294  0.54587014 0.         0.3929732  0.30881281
  0.30141057 0.47101172 0.25902354 0.4946464 ]
 [0.60289054 0.36853539 0.90726716 0.3929732  0.         0.3751869
  0.57703332 0.83999021 0.59962633 0.35499806]
 [0.3499818  0.22683469 0.8220723  0.30881281 0.3751869  0.
  0.25032958 0.74309948 0.56235554 0.22219332]
 [0.14747696 0.46654722 0.66136806 0.30141057 0.57703332 0.25032958
  0.         0.58283816 0.47473302 0.46464993]
 [0.43536184 0.96133948 0.0795272  0.47101172 0.83999021 0.74309948
  0.58283816 0.         0.24462474 0.95351803]
 [0.34558151 0.76313566 0.30785266 0.25902354 0.59962633 0.56235554
  0.47473302 0.24462474

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [84]:
temp = np.array([1.2, 1.3, 2.5, 6.7], dtype=np.float32)
"""
创建 同为32bit，上面用float方法解析，下面利用view创建视图使用int方法解析
"""
temp.view(np.int32) 

array([1067030938, 1067869798, 1075838976, 1087792742])

#### 54. How to read the following file? (★★☆)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [102]:
from io import StringIO
st = StringIO("""
1, 2, 3, 4, 5\n
6,  ,  , 7, 8\n
 ,  , 9,10,11\n""")
np.genfromtxt(st, delimiter=",", dtype=np.int)

array([[ 1,  2,  3,  4,  5],
       [ 6, -1, -1,  7,  8],
       [-1, -1,  9, 10, 11]])

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [96]:
"""
np.ndenumerate:多维数组中的enumerate :返回index和value
np.ndindex: 只返回index
"""
temp = np.array([[4, 5, 6],[6,7,8]])
for index, value in np.ndenumerate(temp):
    print(index, value)
for index in np.ndindex(2, 3):
    print(index)

(0, 0) 4
(0, 1) 5
(0, 2) 6
(1, 0) 6
(1, 1) 7
(1, 2) 8
(0, 0)
(0, 1)
(0, 2)
(1, 0)
(1, 1)
(1, 2)


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [105]:
X, Y = np.meshgrid(np.linspace(-1, 1, 10), np.linspace(-1, 1, 10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
result = np.exp(-(D - mu) ** 2 / (2 * sigma**2) ) #无归一化系数即 \frac{1}{\sqrt{2*pi}*mu}的类高斯分布
result

array([[0.36787944, 0.44822088, 0.51979489, 0.57375342, 0.60279818,
        0.60279818, 0.57375342, 0.51979489, 0.44822088, 0.36787944],
       [0.44822088, 0.54610814, 0.63331324, 0.69905581, 0.73444367,
        0.73444367, 0.69905581, 0.63331324, 0.54610814, 0.44822088],
       [0.51979489, 0.63331324, 0.73444367, 0.81068432, 0.85172308,
        0.85172308, 0.81068432, 0.73444367, 0.63331324, 0.51979489],
       [0.57375342, 0.69905581, 0.81068432, 0.89483932, 0.9401382 ,
        0.9401382 , 0.89483932, 0.81068432, 0.69905581, 0.57375342],
       [0.60279818, 0.73444367, 0.85172308, 0.9401382 , 0.98773022,
        0.98773022, 0.9401382 , 0.85172308, 0.73444367, 0.60279818],
       [0.60279818, 0.73444367, 0.85172308, 0.9401382 , 0.98773022,
        0.98773022, 0.9401382 , 0.85172308, 0.73444367, 0.60279818],
       [0.57375342, 0.69905581, 0.81068432, 0.89483932, 0.9401382 ,
        0.9401382 , 0.89483932, 0.81068432, 0.69905581, 0.57375342],
       [0.51979489, 0.63331324, 0.7344436

#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [16]:
"""
在数组中随机替换P个值
np.put现将array flatten成一维后按照index来替换所输入的值

"""
p = 4
temp = np.zeros([3,3])
np.put(temp, np.random.choice(range(temp.shape[0]**2), 4, replace=False), 100)
temp

array([[  0.,   0., 100.],
       [100.,   0.,   0.],
       [  0., 100., 100.]])

#### 58. Subtract the mean of each row of a matrix (★★☆)

In [33]:
temp = np.array([np.arange(5),np.arange(5,10)], dtype=np.float)
# temp -= np.mean(temp, axis=1).reshape(2,1)
temp -= np.mean(temp, axis=1, keepdims=True)
temp

array([[-2., -1.,  0.,  1.,  2.],
       [-2., -1.,  0.,  1.,  2.]])

#### 59. How to sort an array by the nth column? (★★☆)

In [40]:
temp = np.random.rand(3,3)
np.argsort(temp, axis=0)

array([[2, 1, 2],
       [0, 2, 1],
       [1, 0, 0]], dtype=int64)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [44]:
temp = np.array([0,1,2,3,4])
np.count_nonzero(temp) == temp.shape[0]

False

#### 61. Find the nearest value from a given value in an array (★★☆)

In [54]:
"""
flat可以将Z flatten成一维向量并赋予index值，在一维情况下下面两种情况等价，而二维及以上情况下不使用flat会报错
"""
Z = np.random.uniform(-1,1, 10)
z = 0.5
result = Z[np.abs(Z-z).argmin()]
print(result)
result2 = Z.flat[np.abs(Z-z).argmin()]

0.5681303166188185


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [55]:
"""
i cant understand
"""
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])
for x,y,z in it: z[...] = x + y
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆)

In [57]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")

Z = NamedArray(np.arange(10), "test_array")
print (Z.name)

test_array


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [70]:
"""
题意，以B中元素为index并在A中对应位置加1，可理解为统计B中各元素的数量。
方法一，使用np.bincount统计B中各元素的数量并与A求和
方法二，使用np.add.at直接可以将B中的元素作为index并在A中对应位置加1
"""
matrix_a = np.ones(10)
matrix_b = np.random.randint(0, len(matrix_a), 10)
matrix_a += np.bincount(matrix_b, minlength=len(matrix_a))
matrix_a

matrix_a = np.ones(10)
matrix_b = np.random.randint(0, len(matrix_a), 10)
np.add.at(matrix_a, matrix_b, 1)
matrix_a

array([2., 3., 2., 1., 1., 1., 2., 2., 4., 2.])

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [74]:
"""
将X中相同index的值累加，index由I决定
if a value n is found at position i, out[n] += weight[i] instead of out[n] += 1.
"""
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,weights=X)
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★)

In [55]:
w,h = 16,16
I = np.random.randint(0,2,(h,w,3)).astype(np.ubyte)
#Note that we should compute 256*256 first. 
#Otherwise numpy will only promote F.dtype to 'uint16' and overfolw will occur
F = I[...,0]*(256*256) + I[...,1]*256 +I[...,2] # 可思考处
n = len(np.unique(F))
print(n)

8


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [54]:
A = np.random.randint(0,10,(3,4,3,4))
# print(temp.sum(axis=3).sum(axis=2))
print(A.sum(axis=(-2, -1)))

[[41 70 50 51]
 [60 59 54 56]
 [48 64 48 66]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

In [111]:
"""
存疑
"""
D = np.array(np.arange(10))
S = np.random.randint(0, len(D), 5)
np.mean(np.bincount(np.bincount(S,minlength=10),D))

22.5

#### 69. How to get the diagonal of a dot product? (★★★)

In [112]:
# my answer
np.diag(np.dot(np.array(np.arange(6)).reshape(3,2), np.array(np.arange(6)).reshape(2,3)))

# Author: Mathieu Blondel

A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))

# Slow version  
np.diag(np.dot(A, B))

# Fast version
np.sum(A * B.T, axis=1)

# Faster version
np.einsum("ij,ji->i", A, B)

array([ 3, 14, 33])

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [126]:
matrix_a = np.array([1, 2, 3, 4 ,5])
matrix_b = np.zeros(3*(len(matrix_a)+1)-1)
matrix_b[::4]=matrix_a
matrix_b

array([1., 0., 0., 0., 2., 0., 0., 0., 3., 0., 0., 0., 4., 0., 0., 0., 5.])

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

In [137]:
"""
在切片维度中使用None 效果等同使用np.newaxis 都是在指定位置添一维，
下面matrix_b[:,:, None]之后维度变为(5,5,1)
"""
matrix_a = np.ones([5,5,3])
matrix_b = np.ones([5,5])+1
np.multiply(matrix_a,matrix_b[:,:,np.newaxis])
np.multiply(matrix_a,matrix_b[:,:,None])

(5, 5, 1)

#### 72. How to swap two rows of an array? (★★★)

In [43]:
# Author: Eelco Hoogendoorn

A = np.arange(25).reshape(5,5)
print(A)
A[[0,1]] = A[[1,0]]
print(A)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

In [44]:
# Author: Nicolas P. Rougier

faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

[( 2, 63) ( 2, 92) ( 4, 43) ( 4, 51) ( 4, 59) ( 4, 83) ( 6, 26) ( 6, 39)
 ( 8, 12) ( 8, 45) (12, 45) (18, 22) (18, 31) (18, 47) (18, 72) (20, 34)
 (20, 43) (22, 31) (26, 39) (28, 58) (28, 81) (34, 43) (36, 52) (36, 83)
 (43, 59) (47, 72) (51, 83) (52, 83) (58, 81) (63, 92)]


#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

In [37]:
C = np.bincount(np.random.randint(0,10,10), minlength=10)
A = np.array([])
for index, value in np.ndenumerate(C):
    A= np.append(A, [index]*value)
A = A.astype('int')
np.bincount(A, minlength=10) == C
# Author: Jaime Fernández del Río
"""
按照bincout的结果repeat 序列，其中若为0次则不出现
"""
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C) 

[0 2 1 1 2 0 1]


array([2, 2, 3])

#### 75. How to compute averages using a sliding window over an array? (★★★)

In [34]:
# Author: Jaime Fernández del Río

def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
Z = np.arange(20)
print(moving_average(Z, n=3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★)

In [31]:
Z = np.array(np.arange(9))
from numpy.lib import stride_tricks
stride_tricks.as_strided(Z,(3,3))  # 相当于reshape
Z.reshape(3,3)

# Author: Joe Kington / Erik Rigtorp
from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.itemsize, a.itemsize)
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(10), 3)
print(Z)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [194]:
np.logical_not(True)
np.logical_not(False)
A = np.array([-1,2, 10, 0.3])
np.negative(A,out=A)
A

array([  1. ,  -2. , -10. ,  -0.3])

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

In [29]:
def distance(P0, P1, p):
    T = P1 - P0
    print(T)
    L = (T**2).sum(axis=1)
    print(L)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    print(U)
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    print(D)
    return np.sqrt((D**2).sum(axis=1))

X = np.random.uniform(-10,10,(10,2))
Y = np.random.uniform(-10,10,(10,2))
P  = np.random.uniform(-10,10,(1,2))
print(distance(P0, P1, p))

[[  4.55712225 -10.56478288]
 [ -9.07045452   2.68642488]
 [  8.37255877  -5.97417854]
 [ 10.56029017  10.15049766]
 [  4.35990076  -2.33181325]
 [  2.43890978 -15.5848086 ]
 [ -6.85068699   6.66730425]
 [  6.62283534  11.21587339]
 [ -7.97136     10.65341911]
 [ -3.38986015 -12.40941162]]
[132.38200043  89.49002374 105.7905496  214.55233106  24.4460877
 248.83453996  91.38485825 169.65776395 177.03791902 165.48464848]
[ 0.82283091  0.76096596 -0.06778731 -0.30197652  0.93527609  0.80738468
  0.42659832 -0.02217238  0.39936714  0.94256108]
[[ 2.28975764  0.98768764]
 [ 1.78172945  6.01583765]
 [ 2.09237326  2.9323727 ]
 [-0.10716982  0.11149644]
 [ 4.30835615  8.05553585]
 [ 1.5237627   0.23845784]
 [ 7.87821644  8.09490505]
 [ 7.28475399 -4.30155766]
 [ 4.52462678  3.38552614]
 [ 8.77191298 -2.39621016]]
[ 2.49369544  6.27414237  3.6023375   0.15465066  9.13529368  1.5423083
 11.29574177  8.45996685  5.65102068  9.09330966]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

In [28]:
X = np.random.uniform(-10, 10, (10,2))
Y = np.random.uniform(-10,10,(10,2))
P = np.random.uniform(-10, 10, (10,2))
print(np.array([distance(P0,P1,p_i) for p_i in p]))

[[ 2.49369544  6.27414237  3.6023375   0.15465066  9.13529368  1.5423083
  11.29574177  8.45996685  5.65102068  9.09330966]]


#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

In [6]:
Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)
def extrace_matrix(array, position, shape, fill=0):
    Z = array
    target_shape = shape
    fill  = 0
    target_position = position
    R = np.ones(shape, dtype=Z.dtype)*fill
    P  = np.array(list(position)).astype(int) # 1, 1
    Rs = np.array(list(R.shape)).astype(int) # 5, 5
    Zs = np.array(list(Z.shape)).astype(int) # 10, 10

    R_start = np.zeros((len(shape),)).astype(int) # 0, 0
    R_stop  = np.array(list(shape)).astype(int) #  5, 5

    Z_start = (P-np.floor(Rs/2)).astype('int')  # 1,1 - 2,2= -1,-1
    Z_stop  = (P+np.ceil(Rs/2)).astype('int')   # 1,1 + 2,2 + 1,1 = 4,4

    R_start = (R_start - np.minimum(Z_start,0)).tolist() # 1,1
    Z_start = (np.maximum(Z_start,0)).tolist() # 0,0

    R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist() #5,5
    Z_stop = (np.minimum(Z_stop,Zs)).tolist() #4,4

    r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
    z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]

    R[tuple(r)] = Z[tuple(z)]
    return R
result = extrace_matrix(array=Z, shape=shape, position=position)
result

array([[0, 0, 0, 0, 0],
       [0, 7, 2, 4, 6],
       [0, 0, 1, 1, 0],
       [0, 1, 3, 6, 6],
       [0, 2, 3, 2, 1]])

#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★)

In [30]:
# Author: Stefan van der Walt
from numpy.lib import stride_tricks
Z = np.arange(1,15,dtype=np.int64)
stride = Z.itemsize*np.array([1, 1]) 
"""
原解法中没有使用itemsize 是而是显式的将int32对应到(4,4)上，但选择int64 作为dtype就会出现错误的答案
可以参考：
https://blog.csdn.net/Scc_hy/article/details/82531723
https://blog.csdn.net/shwan_ma/article/details/78244044
"""
R = stride_tricks.as_strided(Z,shape=(11,4), strides=stride)
print(R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★)

In [35]:
"""
使用奇异值分解求矩阵的秩，奇异值分解后 sigma中大于tol（tolerance=1e-10）的值的个数就是原矩阵的秩
np.linalg.matrix_rank也基于奇异值分解
"""
Z = np.random.uniform(0,1,(10,10))
U, S, V = np.linalg.svd(Z) # Singular Value Decomposition  
rank = np.sum(S > 1e-10)
print(rank)
rank = np.linalg.matrix_rank(Z)
print(rank)

10
10


#### 83. How to find the most frequent value in an array?

In [16]:
test = np.random.randint(1,10, 20)
result = np.argmax(np.bincount(test))
result

3

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

In [16]:
from numpy.lib import stride_tricks
Z = np.random.randint(1,10,(10,10))
"""
有待细究
"""
print(Z)
Z = Z[:3*(10//3),:3*(10//3)].copy()
stride = Z.itemsize* np.array([27,3,9,1])
R = stride_tricks.as_strided(Z, (3,3,3,3), stride)
# print(R.shape)
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides) #此处
C

[[9 5 6 4 1 1 4 4 8 5]
 [6 1 1 4 9 9 7 2 4 5]
 [5 8 7 3 3 4 1 5 6 7]
 [4 1 8 8 1 7 1 2 2 8]
 [4 1 7 4 9 6 2 6 7 2]
 [1 6 6 8 5 5 5 8 9 9]
 [9 9 3 6 3 6 8 8 5 5]
 [8 3 3 8 9 1 7 9 3 3]
 [4 5 3 5 6 1 1 8 6 3]
 [9 3 9 4 4 5 4 9 9 9]]


array([[[[9, 5, 6],
         [6, 1, 1],
         [5, 8, 7]],

        [[5, 6, 4],
         [1, 1, 4],
         [8, 7, 3]],

        [[6, 4, 1],
         [1, 4, 9],
         [7, 3, 3]],

        [[4, 1, 1],
         [4, 9, 9],
         [3, 3, 4]],

        [[1, 1, 4],
         [9, 9, 7],
         [3, 4, 1]],

        [[1, 4, 4],
         [9, 7, 2],
         [4, 1, 5]],

        [[4, 4, 8],
         [7, 2, 4],
         [1, 5, 6]]],


       [[[6, 1, 1],
         [5, 8, 7],
         [4, 1, 8]],

        [[1, 1, 4],
         [8, 7, 3],
         [1, 8, 8]],

        [[1, 4, 9],
         [7, 3, 3],
         [8, 8, 1]],

        [[4, 9, 9],
         [3, 3, 4],
         [8, 1, 7]],

        [[9, 9, 7],
         [3, 4, 1],
         [1, 7, 1]],

        [[9, 7, 2],
         [4, 1, 5],
         [7, 1, 2]],

        [[7, 2, 4],
         [1, 5, 6],
         [1, 2, 2]]],


       [[[5, 8, 7],
         [4, 1, 8],
         [4, 1, 7]],

        [[8, 7, 3],
         [1, 8, 8],
         [1, 7, 4]],

    

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★)

In [54]:
"""
创建一个对称矩阵类，有待细究
"""
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)

[[ 1 12 10  8 12]
 [12  4  8  2 13]
 [10  8  4 42  9]
 [ 8  2 42  7 12]
 [12 13  9 12  7]]


#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

In [55]:
p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

In [100]:
Z = np.random.randint(1,10,(16,16))
print(Z)
"""
indices=[0,4,8,12] 表示根据axis从index 0,4累加 从4,8累加..(跟正确的应理解为reduce操作，这里是add所以是累加)
"""
col = np.add.reduceat(Z, indices=[0,4,8,12], axis=1)
result = np.add.reduceat(col,indices=[0,4,8,12], axis=0)
result

[[9 2 3 4 4 2 1 9 2 7 9 7 6 5 9 7]
 [9 3 6 5 4 3 4 5 7 4 7 4 7 4 2 5]
 [2 2 9 8 8 4 5 3 1 1 5 6 6 4 9 3]
 [8 2 6 7 7 4 6 3 8 4 4 1 7 7 6 2]
 [9 1 4 6 3 1 2 2 4 1 1 5 5 6 8 7]
 [7 3 1 7 4 1 3 3 4 8 9 6 7 1 7 2]
 [3 1 8 1 5 6 1 7 8 5 1 9 6 6 2 2]
 [8 5 9 7 2 3 6 5 4 9 4 2 2 5 7 7]
 [7 5 7 3 1 1 4 5 8 5 1 7 9 7 6 7]
 [3 5 1 6 4 3 6 9 7 5 7 9 8 9 7 4]
 [3 2 9 4 6 6 1 8 5 1 9 4 8 1 1 8]
 [2 2 1 6 9 2 4 6 3 8 8 7 3 9 9 5]
 [8 5 1 6 9 9 7 1 7 4 3 5 1 4 6 9]
 [9 1 1 7 7 2 8 8 1 3 9 6 3 4 2 5]
 [5 3 4 9 4 8 9 6 3 7 9 9 9 4 1 8]
 [1 4 3 1 1 1 2 2 4 8 4 5 6 9 8 9]]


array([[ 85,  72,  77,  89],
       [ 80,  54,  80,  80],
       [ 66,  75,  94, 101],
       [ 68,  84,  87,  88]], dtype=int32)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [63]:
def iterate(Z):
    # Count neighbours
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

    # Apply rules
    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)
print(Z)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


#### 89. How to get the n largest values of an array (★★★)

In [5]:
Z = np.random.randint(0,100,(10,10))
n=5
Z.flat[np.argsort(Z,axis=None)[-n:]]

array([93, 93, 95, 97, 99])

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

In [89]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T
    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]


    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[0 0 0]
 [0 0 1]
 [0 1 0]
 [0 1 1]
 [1 0 0]
 [1 0 1]
 [1 1 0]
 [1 1 1]
 [2 0 0]
 [2 0 1]
 [2 1 0]
 [2 1 1]]
0 [1 2 3]
[0 0 0 0 1 1 1 1 2 2 2 2]
1 [4 5]
[0 0 1 1 0 0 1 1 0 0 1 1]
2 [6 7]
[0 1 0 1 0 1 0 1 0 1 0 1]
[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


In [84]:
cartesian(([1, 2, 3], [4, 5], [6, 7]))[:,0]

array([1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3])

#### 91. How to create a record array from a regular array? (★★★)

In [12]:
x1=np.array([1,2,3,4])
x2=np.array(['a','dd','xyz','12'])
x3=np.array([1.1,2,3,4])
r = np.core.records.fromarrays([x1,x2,x3],names='a,b,c')
print(r[1])
print(r['a'])
"""
在2D情况下数字索引为col，显示规定的索引为row
"""
print(r)

(2, 'dd', 2.)
[1 2 3 4]
[(1, 'a', 1.1) (2, 'dd', 2. ) (3, 'xyz', 3. ) (4, '12', 4. )]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

In [19]:
temp = np.random.randint(0,10, 100)

print(temp)
print(np.power(temp, 3))
print(temp**3)
np.einsum('i,i,i->i', temp,temp,temp) # worth studying
"""
np.einsum()
https://docs.scipy.org/doc/numpy-1.15.1/reference/generated/numpy.einsum.html?highlight=einsum#numpy.einsum
https://cloud.tencent.com/developer/article/1369762
"""

[9 1 6 0 1 4 1 4 1 7 2 1 9 9 8 2 6 9 7 7 6 5 1 9 0 8 7 0 4 4 1 4 8 4 6 3 2
 5 3 0 0 0 7 0 4 4 9 9 8 1 0 5 8 7 4 7 8 5 8 7 9 2 6 3 5 9 3 5 7 9 1 6 1 5
 5 8 1 5 3 4 3 2 9 4 3 4 5 0 4 2 4 8 5 0 1 9 7 1 2 3]
[729   1 216   0   1  64   1  64   1 343   8   1 729 729 512   8 216 729
 343 343 216 125   1 729   0 512 343   0  64  64   1  64 512  64 216  27
   8 125  27   0   0   0 343   0  64  64 729 729 512   1   0 125 512 343
  64 343 512 125 512 343 729   8 216  27 125 729  27 125 343 729   1 216
   1 125 125 512   1 125  27  64  27   8 729  64  27  64 125   0  64   8
  64 512 125   0   1 729 343   1   8  27]
[729   1 216   0   1  64   1  64   1 343   8   1 729 729 512   8 216 729
 343 343 216 125   1 729   0 512 343   0  64  64   1  64 512  64 216  27
   8 125  27   0   0   0 343   0  64  64 729 729 512   1   0 125 512 343
  64 343 512 125 512 343 729   8 216  27 125 729  27 125 343 729   1 216
   1 125 125 512   1 125  27  64  27   8 729  64  27  64 125   0  64   8
  64 512 125   0   1 729

array([729,   1, 216,   0,   1,  64,   1,  64,   1, 343,   8,   1, 729,
       729, 512,   8, 216, 729, 343, 343, 216, 125,   1, 729,   0, 512,
       343,   0,  64,  64,   1,  64, 512,  64, 216,  27,   8, 125,  27,
         0,   0,   0, 343,   0,  64,  64, 729, 729, 512,   1,   0, 125,
       512, 343,  64, 343, 512, 125, 512, 343, 729,   8, 216,  27, 125,
       729,  27, 125, 343, 729,   1, 216,   1, 125, 125, 512,   1, 125,
        27,  64,  27,   8, 729,  64,  27,  64, 125,   0,  64,   8,  64,
       512, 125,   0,   1, 729, 343,   1,   8,  27])

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

In [29]:
A = np.random.randint(1, 10, (8, 3))
B = np.random.randint(1, 10, (2, 2))
print(A)
print(B)
ix = np.isin(A,B)
np.where(ix) # 结果矩阵前面为row 后面为col

[[2 5 9]
 [1 8 7]
 [3 2 9]
 [5 8 3]
 [7 3 1]
 [6 2 9]
 [5 7 3]
 [4 2 5]]
[[6 1]
 [4 6]]


(array([1, 4, 5, 7], dtype=int64), array([0, 2, 0, 0], dtype=int64))

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

In [65]:
Z = np.random.randint(0,5,(10,3))
print(Z)
# solution for arrays of all dtypes (including string arrays and record arrays)
E = np.all(Z[:,1:] == Z[:,:-1], axis=1) #头尾个取一个，错开切片，相同则这个vector是equal的
U = Z[~E]
print(U)
# soluiton for numerical arrays only, will work for any number of columns in Z
U = Z[Z.max(axis=1) != Z.min(axis=1),:]
print(U)

[[0 1 4]
 [2 0 2]
 [1 1 0]
 [2 1 0]
 [1 4 0]
 [4 4 0]
 [3 3 3]
 [4 4 2]
 [4 4 2]
 [1 0 0]]
[False False False False False False  True False False False]
[[0 1 4]
 [2 0 2]
 [1 1 0]
 [2 1 0]
 [1 4 0]
 [4 4 0]
 [4 4 2]
 [4 4 2]
 [1 0 0]]
[[0 1 4]
 [2 0 2]
 [1 1 0]
 [2 1 0]
 [1 4 0]
 [4 4 0]
 [4 4 2]
 [4 4 2]
 [1 0 0]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★)

In [39]:
Z  = np.array([1, 63, 4, 19], dtype=np.uint8).reshape(4,1) # 注意数据类型要是unsigned int*
np.unpackbits(Z, axis=1)

array([[0, 0, 0, 0, 0, 0, 0, 1],
       [0, 0, 1, 1, 1, 1, 1, 1],
       [0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0, 0, 1, 1]], dtype=uint8)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

In [66]:
"""
有一个2D矩阵，找到其中unique的rows

"""
uZ = np.unique(Z, axis=0)
print(uZ)

[[0 0 1]
 [0 1 1]
 [1 0 1]
 [1 1 0]]
[[0 0 1]
 [0 1 1]
 [1 0 1]
 [1 1 0]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

In [71]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
inner = np.einsum('i,i',a,b)
mul = np.einsum('i,i->i', a,b)
sum_ = np.einsum('i->',a)
outer = np.einsum('i,j->ij', a, b) 
outer

array([[ 4,  5,  6],
       [ 8, 10, 12],
       [12, 15, 18]])


#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

In [76]:
# Author: Bas Swinckels
"""
理解不能
"""
phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5 # segment lengths
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)                # integrate path
r_int = np.linspace(0, r.max(), 200) # regular spaced path
x_int = np.interp(r_int, r, x)       # integrate path
y_int = np.interp(r_int, r, y)

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

In [81]:
X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1) # the rows which only contain integers

M &= (X.sum(axis=-1) == n) # sum to n.
print(X[M])


[ True  True False]
[[2. 0. 1. 1.]]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)

In [59]:
Z = np.random.randn(100)

In [73]:
N=1000
idx = np.random.randint(0, Z.size, (N, Z.size)) 
means = Z[idx].mean(axis=1)   #直接取得N个平均值
print(np.percentile(means, [2.5, 97.5]))
print(np.quantile(means, [0.025, 0.975]))

[-0.158332    0.21492446]
